update yml

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -7,9 +7,9 @@ on:
   pull_request:
 
 jobs:
-  deploy:
+  check-tf-code-and-create-plan-and-update-pr:
+    if: github.event_name == 'pull_request'
     runs-on: ubuntu-latest
-
     steps:
       - uses: actions/checkout@v3
       - name: Setup AWS CLI for "gh actions" user
@@ -19,45 +19,9 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
-          role-to-assume: arn:aws:iam::464919712823:role/admin-role-gh-actions
-          role-duration-seconds: 1200
-          role-session-name: GithubActionsSession
-      
-      - name: Setup Git
-        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: |
-          git config --global user.name "GitHub Actions Bot"
-          git config --global user.email "<>"
-
-      # - name: Upload working code to s3
-      #   id: s3upload
-      #   if: github.event_name == 'pull_request'
-      #   uses: actions/checkout@v3
-      #   with:
-      #     repository: "ashishjullia/terraform-w-rollback"
-      #     fetch-depth: '0'
-      #     ref: 'main'
-      #     path: s3-upload
-
-      - name: Capture working code
-        id: for-release
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        uses: actions/checkout@v3
-        with:
-          repository: "ashishjullia/terraform-w-rollback"
-          fetch-depth: '0'
-          ref: 'main'
-          path: for-release
-      
-      # - name: Copy current working code to s3 bucket
-      #   if: github.event_name == 'pull_request'
-      #   run: |
-      #     cd s3-upload
-      #     ls
-      #     rm -rf .git
-      #     # zip -r working-code.zip .
-      #     # aws s3 cp working-code.zip s3://tf-test-s3-ashish/working-code/
-      #     date '+%Y%m%d%H%M%S' | xargs -t -I % sh -c '{ git tag "release-%"; gh release create "release-%" --generate-notes --target main; }'
+          # role-to-assume: arn:aws:iam::464919712823:role/admin-role-gh-actions
+          # role-duration-seconds: 1200
+          # role-session-name: GithubActionsSession
 
       - name: Get Terraform Version
         run: |
@@ -69,7 +33,7 @@ jobs:
           terraform_version: $TF_VERSION
 
       # Check Terraform configuration files to a canonical format and style
-      - name: Terraform Format
+      - name: Check Terraform Format
         id: fmt
         run: terraform fmt -check
 
@@ -79,11 +43,11 @@ jobs:
 
       # validates the configuration files in a directory, referring only to the configuration 
       # and not accessing any remote services such as remote state, provider APIs, etc.
-      - name: Terraform Validate
+      - name: Validate Terraform Code
         id: validate
         run: terraform validate
 
-      - name: Terraform Plan
+      - name: Generate Terraform Plan
         id: plan
         # if: github.event_name == 'pull_request'
         if: "steps.init.outcome == 'success' && github.event_name == 'pull_request'"
@@ -125,11 +89,113 @@ jobs:
         if: steps.plan.outcome == 'failure'
         run: exit 1
 
+
+  deploy-to-dev:
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+    runs-on: ubuntu-latest
+    outputs:
+      apply-outcome: ${{ steps.apply.outputs.apply-outcome }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup AWS CLI for "gh actions" user
+        id: ghactions
+        uses: aws-actions/configure-aws-credentials@v1-node16
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          # role-to-assume: arn:aws:iam::464919712823:role/admin-role-gh-actions
+          # role-duration-seconds: 1200
+          # role-session-name: GithubActionsSession
+      
+      - name: Setup Git
+        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: |
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email "<>"
+
+      - name: Capture working code
+        id: for-release
+        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        uses: actions/checkout@v3
+        with:
+          repository: "ashishjullia/terraform-w-rollback"
+          fetch-depth: '0'
+          ref: 'main'
+          path: for-release
+      
+      - name: Get Terraform Version
+        run: |
+          echo "TF_VERSION=$(head -n 1 .terraform-version)" >> $GITHUB_ENV
+
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: $TF_VERSION
+
+      # Check Terraform configuration files to a canonical format and style
+      - name: Check Terraform Format
+        id: fmt
+        run: terraform fmt -check
+
+      - name: Terraform Init
+        id: init
+        run: terraform init
+
+      # validates the configuration files in a directory, referring only to the configuration 
+      # and not accessing any remote services such as remote state, provider APIs, etc.
+      - name: Validate Terraform Code
+        id: validate
+        run: terraform validate
+
+      # - name: Generate Terraform Plan
+      #   id: plan
+      #   # if: github.event_name == 'pull_request'
+      #   if: "steps.init.outcome == 'success' && github.event_name == 'pull_request'"
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
+
+      # # This will only run on a "Pull Request"
+      # - name: Update Pull Request
+      #   uses: actions/github-script@v6
+      #   if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+
+      #       <details><summary>Show Plan</summary>
+
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
+
+      #       </details>
+
+      #       *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+      #       github.rest.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
+
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
       - name: Terraform Apply
         id: apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: |
           terraform apply -auto-approve -input=false
+          echo "apply-outcome=${{ steps.apply.apply-outcome }}" >> $GITHUB_OUTPUT
         continue-on-error: true
 
       - name: If apply successful, create a release
@@ -142,17 +208,43 @@ jobs:
           date '+%Y%m%d%H%M%S' | xargs -t -I % sh -c '{ git tag "release-%"; gh release create "release-%" --generate-notes --target main; }'
         env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+################################################################################################################################################
 
-      - name: latest-code directory
+  prepare-rollback:
+    runs-on: ubuntu-latest
+    environment:
+      name: prepare-rollback
+    outputs:
+      prepare-rollback-outcome: ${{ steps.prepare-rollback.outputs.prepare-rollback-outcome }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup AWS CLI for "gh actions" user
+        id: ghactions
+        uses: aws-actions/configure-aws-credentials@v1-node16
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          # role-to-assume: arn:aws:iam::464919712823:role/admin-role-gh-actions
+          # role-duration-seconds: 1200
+          # role-session-name: GithubActionsSession
+
+      - name: Setup Git
+        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: |
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email "<>" 
+
+      - name: Clone Code to 'latest-code' Directory with depth '0'
         id: latest-code
-        if: steps.apply.outcome == 'failure'
+        # if: steps.apply.outcome == 'failure'
         uses: actions/checkout@v3
         with:
           # repository: 
           fetch-depth: '0'
           path: latest-code
       
-      - name: new directory
+      - name: Clone Code to 'new' Directory
         uses: actions/checkout@v3
         id: new
         if: steps.latest-code.outcome == 'success'
@@ -161,8 +253,8 @@ jobs:
           # fetch-depth: 'HEAD~1'
           path: new
       
-      - name: Setup Code and Rollback
-        id: rollback
+      - name: Setup Terraform Code For Rollback
+        id: prepare-rollback
         if: steps.new.outcome == 'success'
         run: |
           # mkdir working-code
@@ -186,18 +278,38 @@ jobs:
           terraform plan -no-color -input=false -out=rollback.tfplan
           # terraform init
           # terraform apply -auto-approve -input=false
+          echo "prepare-rollback-outcome=${{ steps.prepare-rollback.prepare-rollback-outcome }}" >> $GITHUB_OUTPUT
         env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - uses: trstringer/manual-approval@v1
-        if: steps.rollback.outcome == 'success'
-        id: approval
+
+  rollback:
+    if: ${{ needs.prepare-rollback.outputs.prepare-rollback-outcome }} == 'success'
+    runs-on: ubuntu-latest
+    environment:
+      name: rollback
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup AWS CLI for "gh actions" user
+        id: ghactions
+        uses: aws-actions/configure-aws-credentials@v1-node16
         with:
-          secret: ${{ secrets.TOKEN }}
-          approvers: ashishjullia
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+          # role-to-assume: arn:aws:iam::464919712823:role/admin-role-gh-actions
+          # role-duration-seconds: 1200
+          # role-session-name: GithubActionsSession
+
+      # - uses: trstringer/manual-approval@v1
+      #   if: steps.rollback.outcome == 'success'
+      #   id: approval
+      #   with:
+      #     secret: ${{ secrets.TOKEN }}
+      #     approvers: ashishjullia
 
       - name: Approved Rollback 
-        if: steps.approval.outcome == 'success'
+        # if: steps.approval.outcome == 'success'
         run: |
           cd working-code
           terraform init
